### ISSUE TITLE
k8s context should contain CLUSTER_NAME

### ISSUE THREAD

**Issue by cicdteam** [evanshortiss/neon-kube-previews-manifests#1]
There https://github.com/neondatabase/kube-previews-manifests/blob/main/kind-cluster/setup.sh#L49 k8s context hardcoded as `kind-argocd-previews` 

```console
kind create cluster --name $CLUSTER_NAME >> $LOG_FILE
kubectl config use-context 'kind-argocd-previews' >> $LOG_FILE
```
but it should be `kind-$CLUSTER_NAME`

**Comment by evanshortiss** [comment]
Nice find. I will update it before recording myself demoing this 👍

**Comment by evanshortiss** [comment]
Fixed by https://github.com/neondatabase/kube-previews-manifests/commit/a47e138332481c10003b8a4ae2c0d2dc36e0b150
